name: Python package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

  build1:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "my_value"
    steps:
      - name: pythontext
        run: |
          echo "hii everyone"
          echo "My environment variable is $MY_VARIABLE"
